stages:
  - test
  - build

# 1. Native Windows SAST Job using Bandit
python_sast_windows:
  stage: test
  script:
    - Write-Host "Installing Bandit SAST Analyzer..."
    - pip install bandit
    - Write-Host "Running SAST scan on Python files..."
    # Scans the current directory (-r). Shows Medium/High severity findings.
    - bandit -r . -ll -ii
  # Set to true so the pipeline continues to the build stage even if minor vulnerabilities are found
  allow_failure: true

# 2. Windows Conda & PyInstaller Build
pyinstaller_build:
  stage: build
  variables:
    CONDA_ENV_NAME: "apt-v3-1"
  script:
    - Write-Host "Building Conda Environment..."
    - conda env create -f environment.yml --name $env:CONDA_ENV_NAME --force
    
    - Write-Host "Executing PyInstaller within Conda Environment..."
    # 'conda run' safely executes the command inside the environment without needing 'conda activate'
    - conda run -n $env:CONDA_ENV_NAME pyinstaller main_ex.spec --noconfirm
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
