stages:
  - build

pyinstaller_build:
  stage: build
  variables:
    CONDA_ENV_NAME: "apt-v3-1"
  script:
    - |
      $CondaExe = (Get-Command conda -ErrorAction SilentlyContinue).Source
      if (-not $CondaExe) {
          $StandardPaths = @(
              "$env:USERPROFILE\AppData\Local\miniconda3\condabin\conda.bat",
              "$env:USERPROFILE\miniconda3\condabin\conda.bat",
              "$env:USERPROFILE\anaconda3\condabin\conda.bat",
              "C:\ProgramData\miniconda3\condabin\conda.bat",
              "C:\ProgramData\anaconda3\condabin\conda.bat"
          )
          foreach ($Path in $StandardPaths) {
              if (Test-Path $Path) {
                  $CondaExe = $Path
                  break
              }
          }
      }
    - |
      if (-not $CondaExe) {
          Write-Error "Conda was not found on this machine. Ensure Miniconda or Anaconda is installed."
          exit 1
      } else {
          Write-Host "Conda located at: $CondaExe"
      }

    - |
      & $CondaExe env update -f environment.yml --name $env:CONDA_ENV_NAME --prune
    
    - |
      & $CondaExe run --live-stream -n $env:CONDA_ENV_NAME pyinstaller main_ex.spec --noconfirm
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
